# Generated by Django 4.2.5 on 2024-07-21 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistrack_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='sueldo',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
