# Generated by Django 4.2.5 on 2024-07-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistrack_api', '0003_empleado_salario_hora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100, unique=True)),
                ('clave', models.CharField(max_length=100)),
            ],
        ),
    ]
